[package]
name = "orochimaru"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "orochimaru"
path = "bin/main.rs"

[dependencies]
ecvrf = { version = "1.0.0", path="./ecvrf" }
log = "0.4.17"
env_logger = "0.9.0"
tokio = { version = "1.21.2", features = ["io-util", "io-std", "macros", "rt", "rt-multi-thread", "sync", "signal"] }