[workspace]
members = ["libecvrf", "zkmemory", "node"]
exclude = []
resolver = "2"

[workspace.package]
authors = [
    "Chiro <chiro@orochi.network>",
]
repository = "https://github.com/orochi-network/orochimaru/"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"
keywords = ["verifiable computation", "orochi", "zkp", "vrf", "cryptography", "mpc"]
categories = ["zkp", "cryptography", "distributed", "mpc"]

[profile.bench]
lto = "fat"
codegen-units = 1

