[package]
name = "orochimaru"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "orochimaru"
path = "bin/main.rs"

[features]

[dependencies]
ecvrf = { version = "1.0.0", path="./ecvrf" }
log = "0.4.17"
env_logger = "0.9.0"
tokio = { version = "1.21.2", features = ["full"] }
hyper = { version = "0.14.20", features = ["server", "client", "http1", "tcp", "runtime"] }
hmac = "0.12.1"
serde_json = "1.0.87"
bytes = "1.2.1"
http-body-util = "0.1.0-rc.1"