[package]
name = "zkmemory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "zkmemory"
path = "src/lib.rs"

[dependencies]
cargo-llvm-cov = "0.5.27"
ethnum = "1.3.2"
halo2_proofs = {git="https://github.com/privacy-scaling-explorations/halo2", tag="v2023_04_20"}
hex = "0.4.3"
rbtree = "0.1.5"
